### PR TITLE
Prevent fake player crossbow shooting

### PR DESCRIPTION
**Pull request by S-S-X**
Fix server crash when fake player attempts to shoot crossbow

### CODE REVIEW

**Comment by SmallJoker** [comment]
How is this happening at all? Why is that mod attempting to call `on_used` using a fake player? This is likely to cause bugs in various places, not limited to this mod.

**Comment by S-S-X** [comment]
> How is this happening at all? Why is that mod attempting to call `on_used` using a fake player? This is likely to cause bugs in various places, not limited to this mod.

Pipeworks node breaker for example but I know there's other things allowing similar thing.
Yes, I've fixed similar bug if few other mods like digtron when it is automated using pipeworks and glider when node breaker attempts to grow wings 😄

**Comment by S-S-X** [comment]
With some more code it would probably also be possible to make this feature and actually allow fake player to shoot but pipeworks node breaker ~cannot do that~ requires manual reloading because it does not have inventory for arrows, some other fake player implementation might (_allow fully automated shooting_) but I've not tried those myself. I think probably not worth it.

**Comment by SmallJoker** [comment]
I guess this `on_use` call in pipeworks was implemented to handle the technic drill and laser tools (pipeworks/wielder.lua for reference). That's quite unfortunate, but I cannot figure out any simpler solution at the moment. Will merge this PR in a few days unless there are objections.

**Pull request merged**
